//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLSP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Account
    {
        [Required(ErrorMessage = "Bạn chưa nhập tên đăng nhập")]
        public string username { get; set; }
        [Required(ErrorMessage = "Mật khẩu không chính xác")]
        public string pass { get; set; }
        public Nullable<int> Emp_ID { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
